// Code generated by MockGen. DO NOT EDIT.
// Source: operations.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	domain "github.com/cookienyancloud/avito-backend-test/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockIRepoMain is a mock of IRepoMain interface.
type MockIRepoMain struct {
	ctrl     *gomock.Controller
	recorder *MockIRepoMainMockRecorder
}

// MockIRepoMainMockRecorder is the mock recorder for MockIRepoMain.
type MockIRepoMainMockRecorder struct {
	mock *MockIRepoMain
}

// NewMockIRepoMain creates a new mock instance.
func NewMockIRepoMain(ctrl *gomock.Controller) *MockIRepoMain {
	mock := &MockIRepoMain{ctrl: ctrl}
	mock.recorder = &MockIRepoMainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepoMain) EXPECT() *MockIRepoMainMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockIRepoMain) GetBalance(ctx context.Context, inp *domain.BalanceInput) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, inp)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockIRepoMainMockRecorder) GetBalance(ctx, inp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockIRepoMain)(nil).GetBalance), ctx, inp)
}

// GetTransactionsList mocks base method.
func (m *MockIRepoMain) GetTransactionsList(ctx context.Context, inp *domain.TransactionsListInput) ([]*domain.TransactionsList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionsList", ctx, inp)
	ret0, _ := ret[0].([]*domain.TransactionsList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionsList indicates an expected call of GetTransactionsList.
func (mr *MockIRepoMainMockRecorder) GetTransactionsList(ctx, inp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionsList", reflect.TypeOf((*MockIRepoMain)(nil).GetTransactionsList), ctx, inp)
}

// MakeRemittance mocks base method.
func (m *MockIRepoMain) MakeRemittance(ctx context.Context, inp *domain.RemittanceInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeRemittance", ctx, inp)
	ret0, _ := ret[0].(error)
	return ret0
}

// MakeRemittance indicates an expected call of MakeRemittance.
func (mr *MockIRepoMainMockRecorder) MakeRemittance(ctx, inp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeRemittance", reflect.TypeOf((*MockIRepoMain)(nil).MakeRemittance), ctx, inp)
}

// MakeTransaction mocks base method.
func (m *MockIRepoMain) MakeTransaction(ctx context.Context, inp *domain.TransactionInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeTransaction", ctx, inp)
	ret0, _ := ret[0].(error)
	return ret0
}

// MakeTransaction indicates an expected call of MakeTransaction.
func (mr *MockIRepoMainMockRecorder) MakeTransaction(ctx, inp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeTransaction", reflect.TypeOf((*MockIRepoMain)(nil).MakeTransaction), ctx, inp)
}
